### ISSUE TITLE
✅Feature:이메일 중복 체크

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/2st-shopping-mall-BE#34]
## Description
회원가입시 이메일 데이터를 요청받아 이미 중복되어있는 이메일인지 확인하고 응답을 보내줍니다.

## Todo

- [x] UserController에 요청주소 매핑
- [x] UserService에 중복 체크 로직 구현
- [x] 요청 데이터 받기위한 Requset 클래스, Response 클래스 구현
- [x] 테스트 진행  

## ETC

Response 클래스는 회원탈퇴, 판매자로 변경 등에 같이 쓸 공통 응답 클래스
