### ISSUE TITLE
Issue: 🐞BUG:로그인,회원가입

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/2st-shopping-mall-BE#37]
## Description
요구사항과 일치하지 않는 api 주소와 로그인 필터에서의 모든 HTTP 메소드를 받을 수 있는 버그 발생  

## Todo

- [x] 요구사항과 일치하지 않는 요청 api 주소 수정
- [x] 회원가입 시 받는 데이터 수정
- [x] 로그인 필터에서 모든 HTTP 메소드 요청을 받을 수 없게 수정

## ETC

기타 User 도메인 관련 리팩토링을 진행합니다.
