### ISSUE TITLE
✅Feature:회원탈퇴

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/2st-shopping-mall-BE#40]
## Description
사용자가 회원 탈퇴 요청을 하면, 사용자의 상태를 "삭제" 상태로 변경합니다.

## Todo

- [ ] UserController 회원 탈퇴 api 매핑
- [ ] UserService 회원 탈퇴 로직 구현
- [ ] UserRepository 회원 정보 찾기 쿼리메소드 구현 or 기존 쿼리메소드 수정
- [ ] UserService 회원 가입시 로직 변경 (탈퇴 후 재가입시)
- [ ] Test: 회원 탈퇴 테스트

**Comment by lsy28901** [comment]
## Todo
- [ ] 회원 가입시 이메일 중복체크 로직 수정
