### ISSUE TITLE
✅Feature:판매자로 변경

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/2st-shopping-mall-BE#52]
## Description
사용자의 역할을 판매자로 변경합니다.

## Todo

- [ ] UserController 판매자 변경 요청 api 매핑
- [ ] UserService 에 판매자 변경 로직 구현
- [ ] User 엔티티에 role 변경 메소드 구현

## ETC

판매자로 변경하는게 아니라, 구매자 와 판매자 두개를 번갈아 가며 변경하는 걸로 구현할지 고민했지만
우선 요구사항처럼 판매자로만 변경하는 것으로 만들 예정입니다.
