### ISSUE TITLE
✅Feature: 회원가입 기능

### ISSUE THREAD

**Issue by lsy28901** [08month-team-project/2st-shopping-mall-BE#7]
## Description
사용자가 사용자 정보를 입력해 회원가입을 진행합니다.
입력된 사용자 정보는 데이터베이스에 저장됩니다.

## Todo

- [x] UserConroller를 수정하여 회원가입 요청 api 주소를 매핑
- [x] UserService에 회원가입 로직 구현
- [x] TestCode로 회원가입 기능을 테스트합니다. 

## ETC

회원 가입시 데이터의 유효성 검사를 진행합니다.
